{
    'name': 'JS Frameworks',
    'version': '1.0.0',
    'sequence': '-103',
    'category': 'JS',
    'summary': """JS""",
    'description': """JS""",
    'author': 'Ideenkreise Tech Pvt Ltd',
    'website': "https://www.ideenkreisetech.com",
    'company': 'Ideenkreise Tech Pvt Ltd',
    'maintainer': 'Ideenkreise Tech Pvt Ltd',
    'depends': ['base_accounting_kit'],
    'data': [
        'security/ir.model.access.csv',
        #      'report/report.xml',
        #      'report/reports.xml',
        #      'report/proposal_report.xml',
        #      'report/experience_report.xml',
        #      'report/offer_report.xml',
        #      'views/amc_details.xml',
        #      'views/menu_inherit.xml',
        #      'views/dashboard.xml',
        #      'views/dashboard_inherit.xml',
             'views/view.xml',
        #      'views/template.xml'
    ],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': True,
}